# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'api.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.LabelUser = QtWidgets.QLabel(self.centralwidget)
        self.LabelUser.setGeometry(QtCore.QRect(230, 60, 421, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelUser.setFont(font)
        self.LabelUser.setText("")
        self.LabelUser.setObjectName("LabelUser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEditMessaje = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditMessaje.setGeometry(QtCore.QRect(30, 120, 611, 131))
        self.textEditMessaje.setObjectName("textEditMessaje")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditLink = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLink.setGeometry(QtCore.QRect(30, 290, 611, 22))
        self.lineEditLink.setObjectName("lineEditLink")
        self.pushButtonPublic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPublic.setGeometry(QtCore.QRect(550, 330, 93, 28))
        self.pushButtonPublic.setObjectName("pushButtonPublic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Разместить пост на стене facebook"))
        self.label_2.setText(_translate("MainWindow", "Пользователь facebook:"))
        self.label_3.setText(_translate("MainWindow", "Cообщение:"))
        self.label_4.setText(_translate("MainWindow", "Cсылка:"))
        self.pushButtonPublic.setText(_translate("MainWindow", "Разместить"))
